version: "3"
services:
  operator1:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3030:3030"
    entrypoint: /app
    command:
      [
        "start-operator",
        "--privKey",
        "/data/operator1/encrypted_private_key.json",
        "--password",
        "/data/operator1/password",
      ]
    volumes:
      - ./examples:/data

  operator2:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3031:3030"
    entrypoint: /app
    command:
      [
        "start-operator",
        "--privKey",
        "/data/operator2/encrypted_private_key.json",
        "--password",
        "/data/operator2/password",
      ]
    volumes:
      - ./examples:/data

  operator3:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3032:3030"
    entrypoint: /app
    command:
      [
        "start-operator",
        "--privKey",
        "/data/operator3/encrypted_private_key.json",
        "--password",
        "/data/operator3/password",
      ]
    volumes:
      - ./examples:/data

  operator4:
    image: ssv-dkg:latest
    networks:
      - shared_network
    ports:
      - "3033:3030"
    entrypoint: /app
    command:
      [
        "start-operator",
        "--privKey",
        "/data/operator4/encrypted_private_key.json",
        "--password",
        "/data/operator4/password",
      ]
    volumes:
      - ./examples:/data

  initiator:
    image: ssv-dkg:latest
    depends_on:
      - operator1
      - operator2
      - operator3
      - operator4
    networks:
      - shared_network
    entrypoint: /app
    command:
      [
        "init",
        "--operatorIDs",
        "1,2,3,4",
        "--operatorsInfoPath",
        "/data/docker_operators.json",
        "--depositResultsPath",
        "/data/initiator/output/deposit.json",
        "--ssvPayloadResultsPath",
        "/data/initiator/output/payload.json",
        "--owner",
        "0x81592c3de184a3e2c0dcb5a261bc107bfa91f494",
        "--nonce",
        "1",
        "--withdrawAddress",
        "0100000000000000000000001d2f14d2dffee594b4093d42e4bc1b0ea55e8aa7",
        "--fork",
        "mainnet",
        "--initiatorPrivKey",
        "/data/initiator/encrypted_private_key.json",
        "--initiatorPrivKeyPassword",
        "/data/initiator/password",
      ]
    volumes:
      - ./examples:/data

networks:
  shared_network:
